name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: "Install .NET"
      run: |
        curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh --install-dir /app/opt/dotnet/ --version 5.0.202
    - name: "Build AppDir"
      run: ./build-linux.sh
      working-directory: Distribution
    - name: "Create AppImage"
      run: |
        curl https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage -o appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage FRESHMusicPlayer.AppDir
    - uses: actions/upload-artifact@v1
      name: "Upload Artifact"
      with:
        name: "FRESHMusicPlayer.AppImage"
        path: "./FRESHMusicPlayer-x86_64.AppImage"