name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Install Dependencies"
      run: |
        npm install -g appdmg
    - name: "Build Project"
      run: ./build-macos.sh
      working-directory: Distribution
    - name: "Create Disk Image"
      run: appdmg Distribution/app-dmg-spec.json ./FRESHMusicPlayer.dmg
    - uses: actions/upload-artifact@v1
      name: "Upload Artifact"
      with:
        name: "FRESHMusicPlayer.dmg"
        path: "./FRESHMusicPlayer.dmg"